package davejab.musicplayer.models;

import android.content.ContentResolver;
import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import davejab.musicplayer.models.util.MediaManager;

/**
 * Abstract item class for all models generated from the MediaManager
 *
 * @author davejab
 */
public abstract class Item implements MediaManager.Query {

    private long id;
    private MediaManager mediaManager;
    private String selection = null;
    private String order = null;

    protected Item(ContentResolver contentResolver){
        setMediaManager(new MediaManager(contentResolver));
    }

    /**
     * Abstract method for defining query parameters based on given item.
     * @param item item used to define query parameters
     */
    public abstract void setItemSelection(Item item);

    /**
     * Abstract method for converting cursor generated by media manager to item.
     * @param cursor cursor generated by media manager
     * @return the converted item
     */
    protected abstract Item cursorToItem(Cursor cursor);

    ContentResolver getContentResolver(){
        return getMediaManager().getContentResolver();
    }

    private List<Item> cursorToList(Cursor cursor){
        List<Item> items = new ArrayList<>();
        while(cursor.moveToNext()) {
            items.add(cursorToItem(cursor));
        }
        return items;
    }

    /**
     * Converts object query to list of items.
     * @return list of items
     */
    public List<Item> toList(){
        // Query the media manager using this object
        Cursor cursor = getMediaManager().query(this);
        return cursorToList(cursor);
    }

    void mergeItem(Item item){
        setId(item.getId());
    }

    public long getId(){
        return this.id;
    }
    private MediaManager getMediaManager(){
        return this.mediaManager;
    }
    public String getSelection(){
        return this.selection;
    }
    public String getOrder(){
        return this.order;
    }
    protected void setId(long id){
        this.id = id;
    }
    private void setMediaManager(MediaManager mediaManager){
        this.mediaManager = mediaManager;
    }
    protected void setSelection(String selection){
        this.selection = selection;
    }
    protected void setOrder(String order){
        this.order = order;
    }

}
